# config.yaml
env_config:
  MAP_NAME_LIST: ['THETRACK']
  
  DYNAMIC_FRICTION: 1
  STATIC_FRICTION: 1

  CONSTANT_SPEED: True
  CONSTANT_SPEED_TARGET: 5

  NON_TRAVERSABLE_TERMINATION: True
  
  RESET_RANDOM: False