# config.yaml
env_config:
  MAP_NAME_LIST: ['THETRACK']
  ORIGIN_LIST: [[0, 0], [28, 0], [0, 28], [28, 28]]
  DYNAMIC_FRICTION: 0.75
  STATIC_FRICTION: 0.75

  CONSTANT_SPEED: True
  CONSTANT_SPEED_TARGET: 5

  NON_TRAVERSABLE_TERMINATION: False
  
  RESET_RANDOM: False

  MAX_SPEED_SCALING: 10
  MAX_STEERING_SCALING: 0.40

