# config.yaml
env_config:
  MAP_NAME_LIST: ['ITA']
  ORIGIN_LIST: [[0, 0], [0, 0], [0, 0], [0, 0]]

  # When comparing real data that don't use incremental it must always be set to False
  INCREMENTAL_MODE: True

  MAX_SPEED_INCREMENT: 0.05
  MAX_STEERING_ANGLE_INCREMENT: 0.010
  MAX_SPEED_SCALING: 8
  MAX_STEERING_SCALING: 0.40
  SPEED_OFFSET: 0
  STEERING_OFFSET: 0.0
  VD_ENHANCED: False

  DYNAMIC_FRICTION: 0.7
  STATIC_FRICTION: 0.7
  STD_FRICTION: 0.00
  NUM_BUCKETS_FRICTION: 1000
  RESTITUTION: 0.0

  CONSTANT_SPEED: False
  CONSTANT_SPEED_TARGET: 5

  # usually both true
  NON_TRAVERSABLE_TERMINATION: True
  RESET_RANDOM: True
  PLAY_POLICY: False

  # SIM_DT: Physics simulation time step
  # SIM_DECIMATION: Number of physics steps per simulation step; 
  # The actions, observations, and rewards are computed every SIM_DECIMATION steps, and every SIM_DECIMATION*SIM_DT seconds.
  EPISODE_LENGTH_S_TIMETRIAL: 10
  EPISODE_LENGTH_S_OVERTAKE: 30
  SIM_DT: 0.005
  SIM_DECIMATION: 5
  # SIM_DT: 0.01
  # SIM_DECIMATION: 8

  LEN_S_IDX: 0.1 
  # SIM_DT: 0.003125

  MIN_DELAY_STEERING: 30 #sim dt steps -> 30 (MIN_DELAY_STEERING) * 0.005 s(SIM_DT) = 0.15s delay
  MAX_DELAY_STEERING: 30
  MIN_DELAY_THROTTLE: 10 #sim dt steps
  MAX_DELAY_THROTTLE: 10

  ACTION_HISTORY_LENGTH: 10
  OBS_HISTORY_LENGTH: 10
  REW_HISTORY_LENGTH: 20

  # Overtake is completed if for every step in REW_HISTORY_LENGTH the opponent is ahead by this idx
  # Wall and Opponent collision is signaled after CHECK_IDX steps they actually happened
  PROGRESS_HISTORY_CHECK_IDX: 4
  WALL_COLLISION_CHECK_IDX: 1
  OPPONENT_COLLISION_CHECK_IDX: 1

  # Min distance allowable to walls (otherwise collision)
  WALL_COLLISION_RADIUS: 0.35
  
  # Max progress allowable (in idx), otherwise we consider it corner cutting
  MAX_PROGRESS_IDX: 30 

  # True if lookahed changes with current velocity
  DYNAMIC_LOOKAHEAD: False
  N_HORIZON: 20 # Number of waypoints for horizon
  # Otherwise use constant idx steps (s_horizon = delta_s_idx [0.1m/idx] * N_horizon_idx [idx])
  DELTA_S_IDX: 10
  T_HORIZON: 4

############### OPPONENT OVERTAKE
  OPP_SIZE_RADIUS: 0.20
  OPP_MOVE_DT: 0.1
  OPP_COLLISION_RADIUS: 0.40
  OPP_FRONT_COLLISION_RADIUS: 0.70
  OPP_LAT_COLLISION_RADIUS: 0.45
  CROSS_POS_LIM: 0.25

  OPP_GENERALIZATION: True
  OPP_TRAJ: "min_curv"
  OPPONENT_TRAJ_XY_SHIFT_MAX: 0.3
  OPP_INIT_VEL_SCALING: 0.1
  OPP_MIN_VEL_SCALING: 0.1
  OPP_STD_VEL_SCALING: 0.3
  OPP_VEL_SCALING_INCREMENT: 0.025
  OPP_VEL_SCALING_DECREASE: 0.000
  OT_COLLISION_RATIO_LVL_UP: 0.41
  OT_COLLISION_RATIO_LVL_DOWN: 0.11
  VEL_SCALING_CHECK_STEPS: 100
  
  OPPONENT_STARTS_MOVING_AFTER_STEP: 20
  # OPPONENT_INIT_DISTANCE_IDX: 40
  OPPONENT_INIT_DISTANCE_IDX_MAX: 60
  OPPONENT_INIT_DISTANCE_IDX_MIN: 10
  OPPONENT_FAR_AWAY_IDX: 90
  OPPONENT_OVERTAKEN_IDX: 10
  OPPONENT_ALWAYS_AHEAD_PERCENTAGE: 0.01

  IGNORE_OPPONENT_UNTIL_EP: 0
  STATIC_OPPONENT_UNTIL_EP: 0
