# config.yaml
env_config:
  # MAP_NAME_LIST: ['AUT', 'BAH', 'SPA', 'BRA', 'DAY', 'JED', 'SPE_R', 'SPE', 'THETRACK', 'CTHETRACK_reverse_v0', 'icra25_v6', 'DCRL', 'CHN', 'TEST_1', 'GLC_smile_small', 'GLC_pit_rbring1', 'IND', 'SAU', 'SAU_R', 'OVA', 'OVA_R', 'IND_R', 'KEY', 'TR2', 'TR3', 'CRO_R', 'f', 'SPA', 'HOOK_v0','CTHETRACK_v1']
  MAP_NAME_LIST: ['CIR1']
  # MAP_NAME_LIST: ['BAHRAIN']
  # MAP_NAME_LIST: ['AUT', 'BAH', 'SPA', 'BRA', 'DAY', 'JED', 'SPE_R', 'SPE', 'CTHETRACK_reverse_v0', 'icra25_v6', 'DCRL', 'CHN', 'TEST_1', 'GLC_smile_small', 'GLC_pit_rbring1', 'IND', 'SAU', 'SAU_R', 'OVA', 'OVA_R', 'IND_R', 'KEY', 'TR2', 'TR3']
  RANDOM_SEED: 43
  ORIGIN_LIST: [[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]] 
  TRAJ_VISIBLE: False
  BOUNDARY_VISIBLE: True
  # When comparing real data that don't use incremental it must always be set to False
  INCREMENTAL_MODE: True 
  STEERING_INCREMENTAL_MODE: True 
  # When comparing real data set to false, otherwise true
  NON_TRAVERSABLE_TERMINATION: True
  RESET_RANDOM: True

  # Actutators limit2
  MAX_SPEED_INCREMENT: 0.10 # m/s /dt_decimation
  MAX_STEERING_ANGLE_INCREMENT: 0.10 # rad /dt_decimation
  MAX_SPEED_SCALING: 12
  MAX_STEERING_SCALING: 0.4
  SPEED_SIM_TO_REAL_SCALING: 1.0 # due to wheel radius mismatch, scaling = 1 when radius 0.5, but then on real car velocity obs need to be scaled up so that policy is safer
  STEERING_SIM_TO_REAL_SCALING: 1.0 # due to geometric model mismatch

  SPEED_OFFSET: 0
  STEERING_OFFSET: 0.04
  # Keep false
  VD_ENHANCED: False

  RANDOMIZE_FRICTION: False
  DYNAMIC_FRICTION: 0.8
  STATIC_FRICTION: 0.8
  STD_FRICTION: 0.0
  NUM_BUCKETS_FRICTION: 30000
  RESTITUTION: 0.0

  # increase weight to 1,1, friction 0,7
  RANDOMIZE_BODY_MASS: False
  MIN_MASS_SCALE: 1.0
  MAX_MASS_SCALE: 1.0
  RANDOMIZE_ACTUATOR_STEERING_GAIN: False
  RANDOMIZE_ACTUATOR_THROTTLE_GAIN: False

  # SIM_DT: Physics simulation time step
  # SIM_DECIMATION: Number of physics steps per simulation step; 
  # The actions, observations, and rewards are computed every SIM_DECIMATION steps, and every SIM_DECIMATION*SIM_DT seconds.
  EPISODE_LENGTH_S_TIMETRIAL: 10
  EPISODE_LENGTH_S_OVERTAKE: 100
  SIM_DT: 0.005
  SIM_DECIMATION: 5
  # SIM_DT: 0.01
  # SIM_DECIMATION: 8

  LEN_S_IDX: 0.1 # DON'T CHANGE!
  # SIM_DT: 0.003125

  MIN_DELAY_STEERING: 30 # sim dt steps, e.g. 0.005*40 = 0.20s
  MAX_DELAY_STEERING: 30

  MIN_DELAY_THROTTLE: 5  #sim dt steps
  MAX_DELAY_THROTTLE: 5


  ACTION_HISTORY_LENGTH: 10 # SIM_DT*SIM_DECIMATION*ACTION_HISTORY_LENGTH, e.g 0.005*10*5 = 0.25s
  OBS_HISTORY_LENGTH: 10
  REW_HISTORY_LENGTH: 100

  # Overtake is completed if for every step in REW_HISTORY_LENGTH the opponent is ahead by this idx
  # Wall and Opponent collision is signaled after CHECK_IDX steps they actually happened
  PROGRESS_HISTORY_CHECK_IDX: 3
  WALL_COLLISION_CHECK_IDX: 50
  OPPONENT_COLLISION_CHECK_IDX: 3

  # Min distance allowable to walls (otherwise collision)
  HARD_WALL_COLLISION_RADIUS: 0.18
  SOFT_WALL_COLLISION_RADIUS: 0.28
  # Max progress allowable (in idx), otherwise we consider it corner cutting
  MAX_PROGRESS_IDX: 30 

  # True if lookahed changes with current velocity
  DYNAMIC_LOOKAHEAD: True
  N_HORIZON: 20 # Number of waypoints for horizon
  # Otherwise use constant idx steps (s_horizon = delta_s_idx [0.1m/idx] * N_horizon_idx [idx])
  DELTA_S_IDX: 5 
  T_HORIZON: 4 # [s]

############### OPPONENT OVERTAKE
  OPP_SIZE_RADIUS: 0.20
  OPP_MOVE_DT: 0.1
  OPP_COLLISION_RADIUS: 0.40
  OPP_FRONT_COLLISION_RADIUS: 0.55
  OPP_LAT_COLLISION_RADIUS: 0.30
  CROSS_POS_LIM: 0.15

  OPP_GENERALIZATION: False
  OPP_TRAJ: "min_curv"
  OPPONENT_TRAJ_XY_SHIFT_MAX: 0.0
  OPP_INIT_VEL_SCALING: 0.75
  OPP_MIN_VEL_SCALING: 0.5
  OPP_STD_VEL_SCALING: 0.05
  OPP_VEL_SCALING_INCREMENT: 0.025
  OPP_VEL_SCALING_DECREASE: 0.000
  OT_COLLISION_RATIO_LVL_UP: 0.51
  OT_COLLISION_RATIO_LVL_DOWN: 0.11
  VEL_SCALING_CHECK_STEPS: 100
  
  OPPONENT_STARTS_MOVING_AFTER_STEP: 20
  # OPPONENT_INIT_DISTANCE_IDX: 40
  OPPONENT_INIT_DISTANCE_IDX_MAX: 41
  OPPONENT_INIT_DISTANCE_IDX_MIN: 40
  OPPONENT_FAR_AWAY_IDX: 90
  OPPONENT_OVERTAKEN_IDX: 10
  OPPONENT_ALWAYS_AHEAD_PERCENTAGE: 0.01

  IGNORE_OPPONENT_UNTIL_EP: 0
  STATIC_OPPONENT_UNTIL_EP: 0
